apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
  labels:
    app: config-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server-app
  template:
    metadata:
      labels:
        app: config-server-app
      
    spec:
      containers:
      - name: config-server-app
    
        image: ligmaboys/config-server
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8888

---

apiVersion: v1
kind: Service
metadata:
  name: config-server-service
spec:
  selector:
    app: config-server-app
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8888
    protocol: TCP
