apiVersion: apps/v1
kind: Deployment
metadata:
  name: domain-header-deployment
  labels:
    app: domain-header-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: domain-header-app
  template:
    metadata:
      labels:
        app: domain-header-app
    spec:
      containers:
      - name: domain-header-app
        image: ligmaboys/domain-header-asserter
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
          

---
apiVersion: v1
kind: Service
metadata:
  name: domain-header-service
spec:
  selector:
    app: domain-header-app
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP



