apiVersion: apps/v1
kind: Deployment
metadata:
  name: domain-header-deployment
  labels:
    app: domain-header-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: domain-header-app
  template:
    metadata:
      labels:
        app: domain-header-app
    spec:
      containers:
      - name: domain-header-app
        image: asserter4project.azurecr.io/domain-header:3b5810ed952e887372d8edcdd21c8ddd88ca6d39
        imagePullPolicy: Always
        env:
          - name: DB_HOST
            value: mysql
          - name: DB_NAME
            value: appdatabase
          - name: DB_USER
            value: root
          - name: DB_PASSWORD
            value: root
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
          

---
apiVersion: v1
kind: Service
metadata:
  name: domain-header-service
spec:
  selector:
    app: domain-header-app
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP



