apiVersion: apps/v1
kind: Deployment
metadata:
  name: reclamation-deployment
  labels:
    app: reclamation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reclamation-app
  template:
    metadata:
      labels:
        app: reclamation-app
    spec:
      containers:
      - name: reclamation-app
        image: ligmaboys/complaint-service
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8084


---
apiVersion: v1
kind: Service
metadata:
  name: reclamation-service
spec:
  selector:
    app: reclamation-app
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8084
    protocol: TCP
