apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-server-config-map
  labels:
    app: eureka
data:
  eureka-server-address: http://eureka-0.eureka:8761/eureka

---

apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  selector:
    app: eureka
  ports:
  - port: 8761
    name: eureka

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  selector:
    matchLabels:
      app: myapp
  serviceName: eureka
  replicas: 1 
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: ligmaboys/eureka-server
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef: 
              name: eureka-server-config-map
              key: eureka-server-address

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
  labels: 
    app: eureka
spec:
  selector:
    app: eureka
  type: NodePort
  ports:
  - port: 80
    targetPort: 8761


